### ISSUE TITLE
Python 2.7?

### ISSUE THREAD

**Issue by jpmens** [jalmeroth/homie-python#2]
Forgive my ignorance by not being able to tell at a glance: would this also work on Python 2.7? It seems so to me (but I'll gladly test).

The reason for asking: I believe there are still lots of Python 2.x installations, particularly on older Raspberry Pis which is the kind of platform `homie-python3` would target, I'd say.

**Comment by jalmeroth** [comment]
I originally thought, coming from a Raspi running Arch Linux with Python 3, it would be a good idea to go for Python 3-only. But probably you are right, it might be a good idea to keep it compatible to 2.7 too.

I don't think it will cause too much extra work, except testing both versions.

**Comment by jalmeroth** [comment]
I did a quick test. Except one minor encoding-issue everything seems to work fine in Python 2.7. @jpmens do you see any other issues?

**Comment by jpmens** [comment]
The `temperature` example works fine on 2.7
