### ISSUE TITLE
questions on this version

### ISSUE THREAD

**Issue by prussiap** [jalmeroth/homie-python#27]
Hey,
Clones this and took a peak at the code. This is a way to add any python capable device in the homie universe right?

I'm wanting to build a homie-ota/homie dashboard in python/js/ruby but without re-inventing the wheel since you guys did some good work.

Can you suggest the best way to go about using your library? Looked at the docs and examples but the docs just seem like a re-hash of all the methods and functions. 

I'll probably re-use the node and a few other classes in this but would rather not cannibalize :) .

**Comment by jalmeroth** [comment]
Hey @prussiap,

sorry for my late answer, I was busy with other things. Yes, you are absolutely right this project aims to implement the homie-convention in python. If you want to copy some code, feel free to do so. The license of this projects permits this.

Best regards,
Jan
