### ISSUE TITLE
OTA

### ISSUE THREAD

**Issue by jpmens** [jalmeroth/homie-python#3]
You mentioned to me you were thinking of doing OTA updates via _git_. How would this work? With an _inotify_ type of reloading of my `homie3-app.py`?

You may have seen in [Homie 2.0 wishlist](https://github.com/marvinroger/homie-esp8266/issues/87#issuecomment-223922485) that Marvin is considering doing OTA via MQTT (which I think is grand). Would this be an idea for `homie-python3` as well? I'm thinking along the lines of publishing a blob of Python code, the `homie3-app.py`, say, which, if it can be loaded, replaces the current version (backing up the old version?).

This would make my life easier in [homie-ota](https://github.com/jpmens/homie-ota), as we could possibly manage both systems more or less identically. Just a thought...

**Comment by jalmeroth** [comment]
Well, in the beginning I thought… „Hey it would be a cool idea to do something simple like `git rev-parse HEAD` to compare versions, `git pull` the new version if there is some and simply restart the application.“

But now I think we need to differentiate a bit. I would like to see homie-python becoming a module managed by pip on the long run. So I guess we are talking about the homie-app.py, which is utilizing the homie-python module somehow.

I think we would need to come up with a solution to:
1. notify the application that a new version is available
2. get the new code and store it to a executable file
3. try to restart the application from the new code
4. offer a roll-back, if something is broken

Number 1 and 2 are easy to implement using the techniques that homie-ota provides.

Unfortunately I am not so sure about 3/4. I saw some code to restart an application or spawn a new one. But how can you actually check, if the new version is healthy? Maybe we would need to implement a mechanism (like homie-python-updater) that only handles the update/roll-back process?

**Comment by jpmens** [comment]
The idea of an `updater` sounds clever, but then of course who updates the updater? :-) Just kidding -- that would be part of the OS install/update procedure.

As to roll-back that is going to be pretty difficult. Comparing to homie-esp8266 there is no rollback, so you could force people to test their code before deploying it OTA.

**Comment by jalmeroth** [comment]
homie-python can now be found on https://pypi.python.org/pypi/homie. `pip install homie` will install it.

**Comment by jpmens** [comment]
👍

**Comment by jalmeroth** [comment]
homie-0.1.4 now requires paho-mqtt so that it gets installed too

**Comment by jalmeroth** [comment]
@jpmens I came to the conclusion that homie-python might better not provide an update-mechanism and rather offers a way to subscribe to $ota. This way homie-python.app is free to implement this feature on its own, if needed. I will wait for homie-esp8266 v2 to implement the new way (having the code in the mqtt-message itself) first.
