### ISSUE TITLE
Cannot be stopped with CTL-C

### ISSUE THREAD

**Issue by jpmens** [jalmeroth/homie-python#5]
On Python 2.7, `homie-python` cannot be stopped with CTRL-C.

(Oh, I notice you've changed the name from `homie-python3` to `homie-python`; well done. :-)

**Comment by jalmeroth** [comment]
I found the root-cause of this to be the update timers not being canceled. To quick-fix this, I introduced Homie.quit(). But this is probably not the most pythonic way so I will leave this issue open and dig into this later on.

**Comment by jpmens** [comment]
`Homie.quit()` works. Would an `atexit` handler do the trick?

**Comment by jalmeroth** [comment]
Threads had to be daemonic before atexit kicks in. Thanks for the heads-up!
