### ISSUE TITLE
Large scale project using Homie-python

### ISSUE THREAD

**Issue by psyciknz** [jalmeroth/homie-python#51]
So I have a Paradox Alarm project https://github.com/psyciknz/ParadoxIP150v2  That I use for getting my alarm into OpenHAB and Home Assistant (long story, but I use both).

Just trying to figure out with the homie convention, what would be the best fit for:
PIR Sensors
Reed Switches (these are covered already)
Partitions with multiple arm states (armed_away, armed_night, disarmed etc).

Thoughts how I might do it?

**Comment by jalmeroth** [comment]
You can think of homie-python as „one device“. So one PIR, Reed Switch...
