### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by jalmeroth** [jalmeroth/homie-python#7]
Implement username/password authentication

**Comment by jalmeroth** [comment]
Needs testing

**Comment by jpmens** [comment]
Authentication works: 

![jmbp-2875](https://cloud.githubusercontent.com/assets/60706/16178053/ec0bfc5e-363e-11e6-90c8-10f9d6673e25.png)

👍

**Comment by jalmeroth** [comment]
Thank you!
