### ISSUE TITLE
Exiting should publish a retained $online false

### ISSUE THREAD

**Issue by jpmens** [jalmeroth/homie-python#9]
Be it with or without `Homie.quit()`, I think `homie-python` should publish a retained `$offline false` when it exits to indicate that the "device" actually is offline, irrespective of whether it crashed (i.e. in which case LWT would fire). 

What do you think?

**Comment by jalmeroth** [comment]
Done.

**Comment by jalmeroth** [comment]
Whoops, I overlooked what you actually asked for. I made homie.quit() sending an `$online = false`.
Why would we need a distinction of offline states? Wouldn't one need to take action anyway?

**Comment by jpmens** [comment]
I did not mean distinction; I simply meant if the Python program stops, it
(so the "device") is by definition offline, isn't it? So whether the
program is killed and the broker sends the LWT or the program is terminated
cleanly, the result is "$offline false".

>

**Comment by jpmens** [comment]
Sorry: $online false
>
>

**Comment by jpmens** [comment]
To cut a long story short, [your commit](https://github.com/jalmeroth/homie-python/commit/9d109b88313139a151526e8028cb5a120076c98f) does exactly what I think it should do.
